[project]
name = 'Blockchain-Based-Hotel-Linen-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cost-allocation]
path = 'contracts/cost-allocation.clar'
clarity_version = 2
epoch = 2.5

[contracts.inventory-registration]
path = 'contracts/inventory-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.laundry-tracking]
path = 'contracts/laundry-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.replacement-schedule]
path = 'contracts/replacement-schedule.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
